import scheduleDataset from "../../outputs/schedule-dataset.json";
import { CompanyProfile, ScheduleEntry, ScheduleImageConfig, ScheduleSegment, TravelerProfile } from "@/lib/types";

const rawProfiles = [
  [1, 11, "김규서"],
  [2, 11, "김예주"],
  [3, 11, "박민강"],
  [4, 11, "안동현"],
  [5, 11, "양지훈"],
  [6, 11, "오승빈"],
  [7, 11, "윤형태"],
  [8, 11, "정석진"],
  [9, 12, "강민기"],
  [10, 12, "김경민"],
  [11, 12, "박효빈"],
  [12, 12, "손명민"],
  [13, 12, "이동건B"],
  [14, 12, "이준수A"],
  [15, 12, "표민재"],
  [16, 12, "황현준"],
  [17, 4, "국도현"],
  [18, 4, "김도현A"],
  [19, 4, "김상민"],
  [20, 4, "김주은"],
  [21, 4, "박재현"],
  [22, 4, "한지민"],
  [23, 4, "현승우"],
  [24, 4, "황원준"],
  [25, 16, "유지환"],
  [26, 16, "이강록"],
  [27, 16, "이인혁"],
  [28, 16, "전상훈"],
  [29, 16, "전우진"],
  [30, 16, "최은혁"],
  [31, 16, "홍성연"],
  [32, 16, "한세린"],
  [33, 3, "김동환"],
  [34, 3, "김민재"],
  [35, 3, "김세현"],
  [36, 3, "남주성"],
  [37, 3, "배규현"],
  [38, 3, "이상영"],
  [39, 3, "전혜원"],
  [40, 3, "조현채"],
  [41, 6, "김태훈"],
  [42, 6, "박원희"],
  [43, 6, "이도윤B"],
  [44, 6, "이예준"],
  [45, 6, "주연우"],
  [46, 6, "최수현"],
  [47, 6, "최진우"],
  [48, 6, "하주현"],
  [49, 10, "김민서"],
  [50, 10, "박성현"],
  [51, 10, "송상준"],
  [52, 10, "양원준"],
  [53, 10, "정태영"],
  [54, 10, "조상우"],
  [55, 10, "최민석"],
  [56, 10, "함선우"],
  [57, 14, "김재홍"],
  [58, 14, "김정현"],
  [59, 14, "남성우"],
  [60, 14, "신유찬"],
  [61, 14, "이준수B"],
  [62, 14, "장현규"],
  [63, 14, "전소율"],
  [64, 14, "정서윤"],
  [65, 8, "고윤재"],
  [66, 8, "권이류"],
  [67, 8, "민영환"],
  [68, 8, "백지원"],
  [69, 8, "유준우"],
  [70, 8, "이동건A"],
  [71, 8, "이승환"],
  [72, 8, "이윤재"],
  [73, 7, "김건우"],
  [74, 7, "김민규"],
  [75, 7, "김태한"],
  [76, 7, "서정우"],
  [77, 7, "선재민"],
  [78, 7, "윤예영"],
  [79, 7, "이은우"],
  [80, 7, "최서원"],
  [81, 9, "박민서"],
  [82, 9, "박수민"],
  [83, 9, "송혁규"],
  [84, 9, "신연우"],
  [85, 9, "윤승준"],
  [86, 9, "이승주"],
  [87, 9, "정승환"],
  [88, 9, "정유성"],
  [89, 13, "김도현B"],
  [90, 13, "박수아"],
  [91, 13, "박진서"],
  [92, 13, "이도윤A"],
  [93, 13, "이정은"],
  [94, 13, "이해랑"],
  [95, 13, "전무성"],
  [96, 13, "진가윤"],
  [97, 2, "김동욱"],
  [98, 2, "남민서"],
  [99, 2, "배성재"],
  [100, 2, "이지후"],
  [101, 2, "임규민"],
  [102, 2, "정다울"],
  [103, 2, "정원우"],
  [104, 2, "조무겸"],
  [105, 5, "김경수"],
  [106, 5, "김수형"],
  [107, 5, "김여민"],
  [108, 5, "김은우"],
  [109, 5, "박성원"],
  [110, 5, "신준우"],
  [111, 5, "임현지"],
  [112, 5, "조하연"],
  [113, 1, "김동언"],
  [114, 1, "류궁"],
  [115, 1, "박소윤"],
  [116, 1, "윤희건"],
  [117, 1, "이준호"],
  [118, 1, "조선하"],
  [119, 1, "최민준"],
  [120, 1, "최여원"],
  [121, 1, "하태혁"],
  [122, 15, "고유석"],
  [123, 15, "김병준"],
  [124, 15, "박서인"],
  [125, 15, "안현준"],
  [126, 15, "이윤우"],
  [127, 15, "장우진"],
  [128, 15, "최준석"],
  [129, 15, "최시후"],
] as const;

export const travelerProfiles: TravelerProfile[] = rawProfiles.map(([rowNumber, groupNumber, name]) => ({
  id: `traveler-${rowNumber}`,
  rowNumber,
  name,
  groupNumber,
  groupLabel: `${groupNumber}조`,
  vehicle:
    rowNumber <= 32
      ? "1호차"
      : rowNumber <= 64
        ? "2호차"
        : rowNumber <= 112
          ? "3호차"
          : "4호차",
}));

export const quickPickNames = ["민영환", "안동현", "김민서", "박성원"];

export const groupOptions = Array.from(
  new Set(travelerProfiles.map((profile) => profile.groupNumber)),
).sort((left, right) => left - right);

export const scheduleImage: ScheduleImageConfig = {
  src: "/schedule-table.jpeg",
  width: 2160,
  height: 3055,
  headerTop: 0,
  headerHeight: 62,
  rowTop: 60,
  rowHeight: 22,
};

export const scheduleSegments: ScheduleSegment[] = [
  {
    id: "segment-1",
    title: "6/23 ~ 6/24 오전",
    subtitle: "출국 · 첫 이동 · 오전 방문",
    x: 150,
    width: 480,
  },
  {
    id: "segment-2",
    title: "6/24 오후 ~ 6/25",
    subtitle: "오후 방문 · 저녁 이동 · 다음날 일정",
    x: 630,
    width: 480,
  },
  {
    id: "segment-3",
    title: "6/26",
    subtitle: "브리지바이오 · 시스코 · 베어로보틱스/구글",
    x: 1110,
    width: 430,
  },
  {
    id: "segment-4",
    title: "6/26 오후 ~ 6/28",
    subtitle: "몰로코/인앤아웃 · 치폴레 · BBQ · 공항",
    x: 1540,
    width: 500,
  },
];

const scheduleSlotLabels: Record<string, string> = {
  "6.23_점심자유식": "6/23 점심",
  "6.23_석식": "6/23 저녁",
  "6.24_오전": "6/24 오전",
  "6.24_중식": "6/24 점심",
  "버스_교체": "버스 교체",
  "6.24_오후": "6/24 오후",
  "6.24_석식": "6/24 저녁",
  "6.25_점심자유식": "6/25 점심",
  "6.25_석식자유식": "6/25 저녁",
  "6.26_오전": "6/26 오전",
  "6.26_중식자유식": "6/26 점심",
  "6.26_오후": "6/26 오후",
  "6.26_석식": "6/26 저녁",
  "6.27_점심자유식": "6/27 점심",
  "6.27": "6/27 저녁",
  "6.28": "6/28",
};

const companyDirectory: Record<string, CompanyProfile> = {
  스탠포드: {
    slug: "stanford-university",
    placeLabel: "스탠포드",
    officialName: "Stanford University",
    category: "University · Research",
    summary: "실리콘밸리 창업 생태계와 가장 강하게 연결된 대표 연구중심 대학이다.",
    keywords: ["Startup", "Computer Science", "Ecosystem"],
    whyItMatters: "기술 연구가 창업과 투자 생태계로 어떻게 이어지는지 현장에서 보기 좋다.",
    whatToWatch: ["학문과 창업 문화의 연결 방식", "캠퍼스가 지역 혁신 허브로 작동하는 구조"],
  },
  UC버클리: {
    slug: "university-of-california-berkeley",
    placeLabel: "UC버클리",
    officialName: "University of California, Berkeley",
    category: "University · Research",
    summary: "공학, AI, 반도체, 창업 연구 역량이 강한 미국 서부 대표 공립 연구대학이다.",
    keywords: ["AI", "Engineering", "Public Research"],
    whyItMatters: "공공 연구기관이 산업 인재와 기술 생태계에 어떤 영향을 주는지 읽기 좋다.",
    whatToWatch: ["연구 중심 대학의 산업 연결 방식", "학생·연구실·창업 네트워크의 밀도"],
  },
  PnP: {
    slug: "plug-and-play-tech-center",
    placeLabel: "PnP",
    officialName: "Plug and Play Tech Center",
    category: "Innovation Platform",
    summary: "스타트업, 대기업, 투자사를 연결하는 글로벌 액셀러레이터이자 혁신 플랫폼이다.",
    keywords: ["Accelerator", "Startup", "VC"],
    whyItMatters: "초기 스타트업이 대기업과 투자 네트워크를 통해 성장하는 구조를 이해하기 좋다.",
    whatToWatch: ["오픈이노베이션 운영 방식", "스타트업 선발과 연결 구조"],
  },
  블룸에너지: {
    slug: "bloom-energy-corporation",
    placeLabel: "블룸에너지",
    officialName: "Bloom Energy Corporation",
    category: "Climate Tech",
    summary: "고체산화물 연료전지 기반 분산형 에너지 솔루션을 만드는 기후테크 기업이다.",
    keywords: ["Fuel Cell", "Energy", "Decarbonization"],
    whyItMatters: "AI 시대 전력 수요 확대와 함께 에너지 인프라 기업의 중요성을 이해할 수 있다.",
    whatToWatch: ["전력 문제를 푸는 제품 관점", "기후테크가 B2B 시장에 들어가는 방식"],
  },
  브리즈바이오: {
    slug: "bridgebio-pharma",
    placeLabel: "브리즈바이오",
    officialName: "BridgeBio Pharma, Inc.",
    category: "Biotech",
    summary: "유전성 질환과 난치질환 치료제를 개발하는 바이오 의약품 기업이다.",
    keywords: ["Biotech", "Drug Development", "Rare Disease"],
    whyItMatters: "딥테크형 바이오 기업이 긴 개발 주기와 높은 규제 장벽을 어떻게 넘는지 보기 좋다.",
    whatToWatch: ["연구 파이프라인 설명 방식", "임상·사업화 단계의 차이"],
  },
  시스코: {
    slug: "cisco-systems",
    placeLabel: "시스코",
    officialName: "Cisco Systems, Inc.",
    category: "Enterprise Infrastructure",
    summary: "네트워크 장비, 보안, 협업 솔루션을 제공하는 엔터프라이즈 인프라 기업이다.",
    keywords: ["Networking", "Security", "Enterprise"],
    whyItMatters: "인터넷과 기업 IT의 기반이 되는 인프라 비즈니스가 어떻게 확장되는지 이해하기 좋다.",
    whatToWatch: ["하드웨어와 소프트웨어 결합 전략", "B2B 매출 구조와 고객 락인"],
  },
  구글: {
    slug: "google",
    placeLabel: "구글",
    officialName: "Google LLC",
    category: "Big Tech",
    summary: "검색, 광고, 클라우드, Android, AI 제품을 운영하는 글로벌 플랫폼 기업이다.",
    keywords: ["AI", "Cloud", "Platform"],
    whyItMatters: "플랫폼·데이터·AI가 결합된 대형 기술 기업의 운영 방식을 읽기 좋다.",
    whatToWatch: ["AI를 제품에 녹이는 방식", "플랫폼 비즈니스와 인프라의 결합"],
  },
  NVIDIA: {
    slug: "nvidia",
    placeLabel: "NVIDIA",
    officialName: "NVIDIA Corporation",
    category: "AI Infrastructure",
    summary: "GPU와 AI 컴퓨팅 플랫폼을 중심으로 성장한 반도체·인프라 기업이다.",
    keywords: ["GPU", "AI", "Semiconductor"],
    whyItMatters: "생성형 AI 붐의 핵심 인프라 기업이 어떤 기술·생태계 우위를 갖는지 이해할 수 있다.",
    whatToWatch: ["칩을 넘어 플랫폼으로 확장하는 전략", "개발자 생태계와 시장 지배력"],
  },
  베어로보틱스: {
    slug: "bear-robotics",
    placeLabel: "베어로보틱스",
    officialName: "Bear Robotics, Inc.",
    category: "Robotics",
    summary: "서비스 로봇을 통해 외식·상업 공간의 운영 효율을 높이는 로보틱스 기업이다.",
    keywords: ["Robotics", "Automation", "Service"],
    whyItMatters: "AI가 물리 세계의 운영 문제와 결합될 때 어떤 제품이 나오는지 보기 좋다.",
    whatToWatch: ["현장 문제를 제품으로 번역한 방식", "하드웨어와 소프트웨어 통합 경험"],
  },
  몰로코: {
    slug: "moloco",
    placeLabel: "몰로코",
    officialName: "Moloco, Inc.",
    category: "AI Software",
    summary: "머신러닝 기반 광고·커머스 최적화 소프트웨어를 만드는 AI 기업이다.",
    keywords: ["Machine Learning", "Ad Tech", "Optimization"],
    whyItMatters: "AI가 실제 매출과 성과 지표를 어떻게 끌어올리는지 보여주는 B2B SaaS 사례다.",
    whatToWatch: ["ML이 제품 성과로 연결되는 구조", "데이터 기반 의사결정 문화"],
  },
  조비: {
    slug: "joby-aviation",
    placeLabel: "조비",
    officialName: "Joby Aviation, Inc.",
    category: "Advanced Mobility",
    summary: "전기 수직이착륙 항공기 eVTOL을 개발하는 미래 모빌리티 기업이다.",
    keywords: ["eVTOL", "Mobility", "Aerospace"],
    whyItMatters: "하드웨어, 규제, 인프라가 모두 얽힌 초고난도 산업을 어떻게 푸는지 볼 수 있다.",
    whatToWatch: ["기술 완성도와 상용화 간격", "규제 산업에서의 실행 전략"],
  },
  "SK Hynix": {
    slug: "sk-hynix",
    placeLabel: "SK Hynix",
    officialName: "SK hynix Inc.",
    category: "Semiconductor",
    summary: "메모리 반도체를 중심으로 AI 시대 핵심 부품을 공급하는 글로벌 반도체 기업이다.",
    keywords: ["Memory", "HBM", "Semiconductor"],
    whyItMatters: "AI 경쟁력이 결국 반도체 공급망과 연결된다는 점을 이해하기 좋다.",
    whatToWatch: ["메모리 반도체의 역할", "AI 인프라와 공급망 연결성"],
  },
  세일즈포스: {
    slug: "salesforce",
    placeLabel: "세일즈포스",
    officialName: "Salesforce, Inc.",
    category: "Enterprise SaaS",
    summary: "CRM을 중심으로 기업용 클라우드 소프트웨어 시장을 키운 대표 SaaS 기업이다.",
    keywords: ["CRM", "SaaS", "Enterprise"],
    whyItMatters: "반복적 기업 업무를 소프트웨어로 표준화하는 SaaS 모델을 이해하기 좋다.",
    whatToWatch: ["플랫폼 확장 전략", "엔터프라이즈 소프트웨어의 락인 구조"],
  },
  망고부스트: {
    slug: "mango-boost",
    placeLabel: "망고부스트",
    officialName: "Mango Boost",
    category: "Visit Spot",
    summary: "원본 일정표 기준 방문지로 반영된 항목이다.",
    keywords: ["Visit", "Schedule", "To Verify"],
    whyItMatters: "현재 데이터셋에는 포함돼 있지만 정식 영문 법인명은 추가 검증이 필요하다.",
    whatToWatch: ["현장 표기와 공식 영문명 일치 여부", "이 장소가 기업 방문인지 식음료 일정인지 재확인"],
  },
};

const rawScheduleRows = scheduleDataset as Array<Record<string, string>>;

export const itineraryByTraveler = Object.fromEntries(
  rawScheduleRows.map((row) => {
    const entries = Object.entries(row)
      .filter(([key, value]) => !["vehicle", "number", "group", "name"].includes(key) && value.trim())
      .map(([slotKey, rawLabel], index) => {
        const placeLabel = rawLabel.replace(/\s*\([^)]*\)$/, "").trim();
        const company = companyDirectory[placeLabel];

        return {
          id: `${row.number}-${slotKey}-${index}`,
          slotKey,
          slotLabel: scheduleSlotLabels[slotKey] ?? slotKey,
          rawLabel,
          displayLabel: company?.officialName ?? placeLabel,
          isCompanyVisit: Boolean(company),
          company,
        } satisfies ScheduleEntry;
      });

    return [row.name, entries];
  }),
) as Record<string, ScheduleEntry[]>;
